homeassistant: !include home-assistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
my:
template: !include_dir_merge_list templates/
sensor: !include_dir_merge_list sensors/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest: !include rest/qualite-eau.yaml
# turn up logging
logger:
  default: info
#
zha_toolkit:
# enable updates
zha:
  zigpy_config:
    ota:
#       otau_directory: /config/zigpy_ota
      extra_providers:
        - type: zigpy_remote
          url: https://github.com/Koenkk/zigbee-OTA/blob/master/index.json
          manufacturer_ids: [0x4151]
#        - type: advanced  # !!! Please read the message below before enabling OTA updates from raw OTA files !!!
#          warning: I understand I can *destroy* my devices by enabling OTA updates from
#            files. Some OTA updates can be mistakenly applied to the wrong
#            device, breaking it. I am consciously using this at my own risk.
#          path: /config/zigpy_ota
#switch:
#  - platform: wake_on_lan
#    name: "Console"
#    mac: D8:F8:83:36:0B:73
#    turn_off:
#      action: shell_command.turn_off_console
#shell_command:
#  turn_off_console: "ssh root@192.168.1.74 pm-suspend"

# recorder - ajoute le 2026-08-16
recorder:
  purge_keep_days: 10
  commit_interval: 5
  exclude:
    entity_globs:
      - sensor.*_linkquality
      - sensor.*_rssi
      - sensor.*_uptime
      - sensor.*_last_seen
    entities:
      - sensor.date
      - sensor.time
