- platform: snmp
  name: "Printer uptime"
  host: 192.168.1.2
  baseoid: 1.3.6.1.2.1.1.3.0
  accept_errors: true
  default_value: 0
  unit_of_measurement: "minutes"
  value_template: "{{ ((value | int(0)) / 6000) | int(0) }}"
